version: '3.9'

services:
  db:
    image: postgres:16.0-alpine3.17
    container_name: cats-db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: cats
    ports:
      - 5432:5432
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  # https://github.com/localstack/localstack/blob/master/docker-compose.yml
  # https://docs.localstack.cloud/get-started/#docker-compose
  localstack:
    container_name: cats-localstack
    image: localstack/localstack:0.13
    ports:
      - '4566-4599:4566-4599'
      - '${PORT_WEB_UI-8081}:${PORT_WEB_UI-8080}'
    environment:
      - AWS_DEFAULT_REGION=eu-central-1
      - AWS_ACCESS_KEY_ID=cats
      - AWS_SECRET_ACCESS_KEY=cats
      - SERVICES=s3
    volumes:
      - '${TMPDIR:-/tmp}/localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './localstack:/docker-entrypoint-initaws.d:ro'